import { writeFile, unlink, readFile } from "fs/promises";
import { existsSync } from "fs";
import { execFile } from "child_process";
import { promisify } from "util";
import { log } from "./logger.js";

const execFileAsync = promisify(execFile);

const NGINX_PROJECTS_DIR = "/var/www/scws/nginx/projects";

function generateProjectConfig(name: string, port: number): string {
  return `# Project: ${name} (port ${port})
# Auto-generated by SCWS daemon — do not edit manually
location /${name}/ {
    proxy_pass http://127.0.0.1:${port}/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Base-Path /${name};
    proxy_read_timeout 300s;
    proxy_connect_timeout 10s;
}
`;
}

function generateNextConfig(name: string, port: number): string {
  // Next.js with basePath: match both /name and /name/... in a single location.
  // Use regex to avoid trailing-slash redirect loops.
  // proxy_pass without trailing slash preserves the original URI path.
  return `# Project: ${name} (Next.js, port ${port})
# Auto-generated by SCWS daemon — do not edit manually
location ~ ^/${name}(/.*)?$ {
    proxy_pass http://127.0.0.1:${port};
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 300s;
    proxy_connect_timeout 10s;
}
`;
}

export async function addProjectNginx(name: string, port: number, framework?: string): Promise<void> {
  const configPath = `${NGINX_PROJECTS_DIR}/${name}.conf`;
  const config = framework === "next"
    ? generateNextConfig(name, port)
    : generateProjectConfig(name, port);

  await writeFile(configPath, config, "utf-8");
  log(`Wrote nginx config: ${configPath}`, "nginx");

  await testAndReload();
}

export async function removeProjectNginx(name: string): Promise<void> {
  const configPath = `${NGINX_PROJECTS_DIR}/${name}.conf`;
  if (existsSync(configPath)) {
    await unlink(configPath);
    log(`Removed nginx config: ${configPath}`, "nginx");
    await testAndReload();
  }
}

async function testAndReload(): Promise<void> {
  // Test config
  const { stderr: testErr } = await execFileAsync("nginx", ["-t"], { timeout: 10_000 });
  if (testErr && !testErr.includes("test is successful")) {
    log(`nginx config test failed: ${testErr}`, "error");
    throw new Error(`nginx config test failed: ${testErr}`);
  }

  // Reload
  await execFileAsync("systemctl", ["reload", "nginx"], { timeout: 10_000 });
  log("nginx reloaded", "nginx");
}

export async function getNginxStatus(): Promise<string> {
  try {
    const { stdout } = await execFileAsync("systemctl", ["is-active", "nginx"], { timeout: 5_000 });
    return stdout.trim();
  } catch {
    return "unknown";
  }
}
